app:
  app_port: ":11011"
auth:
  hash_salt: "salt" # Соль для хэширования паролей
database:
  db_host: "127.0.0.1"
  db_port: "5432"
  db_user: "-"
  db_password: "-"
  db_name: "-"
  db_ssl_mode: "disable"
tls:
  ssl_mode: false
  ssl_cert_file: "-"
  ssl_key_file: "-"
